In [ ]:
Tess=pd.read_csv('/content/Tess.csv')

In [ ]:
Tess['tfopwg_disp'].value_counts()

tfopwg_disp
PC    4678
FP    1196
CP     683
Name: count, dtype: int64

In [ ]:
mask = ~((Tess['tfopwg_disp'] == 'FA') | (Tess['tfopwg_disp'] == 'APC')| (Tess['tfopwg_disp'] == 'KP'))
Tess = Tess[mask].copy()

tfopwg_disp
PC    4678
CP    1266
FP    1196
Name: count, dtype: int64

In [ ]:
Tess['tfopwg_disp'].count()

np.int64(7140)

In [ ]:
Tess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7699 entries, 0 to 7698
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rowid        7699 non-null   int64
 1   toi          7699 non-null   float64
 2   toipfx       7699 non-null   int64
 3   tid          7699 non-null   int64
 4   ctoi_alias   7699 non-null   float64
 5   pl_pnum      7699 non-null   int64
 6   tfopwg_disp  7699 non-null   object
 7   rastr        7699 non-null   object
 8   ra           7699 non-null   float64
 9   decstr       7699 non-null   object
 10  dec          7699 non-null   float64
 11  st_pmra      7565 non-null   float64
 12  st_pmdec     7565 non-null   float64
 13  pl_tranmid   7699 non-null   float64
 14  pl_orbper    7592 non-null   float64
 15  pl_trandurh  7699 non-null   float64
 16  pl_trandep   7699 non-null   float64
 17  pl_rade      7193 non-null   float64
 18  pl_insol     7523 non-null   float64
 19  pl_eqt       7388 non-null   float64
 20  st_tmag      7699 non-null   float64
 21  st_dist      7484 non-null   float64
 22  st_teff      7538 non-null   float64
 23  st_logg      6843 non-null   float64
 24  st_rad       7192 non-null   float64
 25  toi_created  7699 non-null   object
 26  rowupdate    7699 non-null   object
dtypes: float64(18), int64(4), object(5)
memory usage: 1.6+ MB

In [ ]:
Tess

,rowid,toi,toipfx,tid,ctoi_alias,pl_pnum,tfopwg_disp,rastr,ra,decstr,...,pl_rade,pl_insol,pl_eqt,st_tmag,st_dist,st_teff,st_logg,st_rad,toi_created,rowupdate
0,1,1000.01,1000,50365310,5.036531e+07,1,FP,07h29m25.85s,112.357708,-12d41m45.46s,...,5.818163,22601.948580,3127.204052,9.604000,485.735,10249.0,4.19,2.169860,7/24/2019 15:58,9/9/2024 10:08
1,2,1001.01,1001,88863718,8.886372e+07,1,PC,08h10m19.31s,122.580465,-05d30m49.87s,...,11.215400,44464.500000,4045.000000,9.423440,295.862,7070.0,4.03,2.010000,7/24/2019 15:58,4/3/2023 14:31
2,3,1002.01,1002,124709665,1.247097e+08,1,FP,06h58m54.47s,104.726966,-10d34m49.64s,...,23.752900,2860.610000,2037.000000,9.299501,943.109,8924.0,NaN,5.730000,7/24/2019 15:58,7/11/2022 16:02
3,4,1003.01,1003,106997505,1.069975e+08,1,FP,07h22m14.39s,110.559945,-25d12m25.26s,...,NaN,1177.360000,1631.000000,9.300300,7728.170,5388.5,4.15,NaN,7/24/2019 15:58,2/23/2022 10:10
4,5,1004.01,1004,238597883,2.385979e+08,1,FP,08h08m42.77s,122.178195,-48d48m10.12s,...,11.311300,54679.300000,4260.000000,9.135500,356.437,9219.0,4.14,2.150000,7/24/2019 15:58,9/9/2024 10:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,7695,995.01,995,317951248,3.179512e+08,1,FP,07h23m14.75s,110.811443,+05d33m46.26s,...,NaN,1413.670000,1708.000000,10.078100,1080.880,4805.2,NaN,NaN,7/24/2019 15:58,10/29/2021 12:59
7695,7696,996.01,996,142918609,1.429186e+08,1,FP,07h57m23.99s,119.349948,-19d30m57.65s,...,16.052300,NaN,NaN,9.792500,379.693,8007.0,NaN,2.050000,7/24/2019 15:58,10/29/2021 12:59
7696,7697,997.01,997,341729521,3.417295e+08,1,FP,08h05m16.69s,121.319521,-59d34m47.27s,...,20.510696,127.916421,857.731431,9.772700,113.667,5786.0,4.52,0.926261,7/24/2019 15:58,9/9/2024 10:08
7697,7698,998.01,998,54390047,5.439005e+07,1,FP,07h53m16.69s,118.319555,-14d13m07.76s,...,4.529209,41562.587810,3641.626449,9.695200,482.278,8322.0,4.01,2.349860,7/24/2019 15:58,9/9/2024 10:08
7698,7699,999.01,999,341186896,3.411869e+08,1,FP,07h55m27.38s,118.864086,-58d13m19.42s,...,5.530910,9662.800000,2762.000000,9.617100,180.020,6635.0,4.35,1.300000,7/24/2019 15:58,9/9/2024 10:08

In [ ]:

Tess = Tess.drop(columns=["toi_created", "rowupdate","rowid"])

In [ ]:
Tess.isna().sum()

toi              0
toipfx           0
tid              0
ctoi_alias       0
pl_pnum          0
tfopwg_disp      0
rastr            0
ra               0
decstr           0
dec              0
st_pmra        114
st_pmdec       114
pl_tranmid       0
pl_orbper       89
pl_trandurh      0
pl_trandep       0
pl_rade        452
pl_insol       158
pl_eqt         258
st_tmag          0
st_dist        174
st_teff        148
st_logg        755
st_rad         453
dtype: int64

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

threshold = 0.5
missing_ratio = Tess.isnull().mean()
cols_to_drop = missing_ratio[missing_ratio > threshold].index
Tess = Tess.drop(columns=cols_to_drop)
print(f"Dropped columns: {list(cols_to_drop)}")


num_cols = Tess.select_dtypes(include=["float64", "int64"]).columns
iter_imputer = IterativeImputer(random_state=42)
Tess[num_cols] = iter_imputer.fit_transform(Tess[num_cols])


cat_cols = Tess.select_dtypes(include=["object"]).columns
cat_imputer = SimpleImputer(strategy="most_frequent")
Tess[cat_cols] = cat_imputer.fit_transform(Tess[cat_cols])

Tess.isnull().sum()

Dropped columns: []

toi            0
toipfx         0
tid            0
ctoi_alias     0
pl_pnum        0
tfopwg_disp    0
rastr          0
ra             0
decstr         0
dec            0
st_pmra        0
st_pmdec       0
pl_tranmid     0
pl_orbper      0
pl_trandurh    0
pl_trandep     0
pl_rade        0
pl_insol       0
pl_eqt         0
st_tmag        0
st_dist        0
st_teff        0
st_logg        0
st_rad         0
dtype: int64

In [ ]:
Tess.shape

(7140, 24)

In [ ]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder

X = Tess.drop(columns=["tfopwg_disp"])
y = Tess["tfopwg_disp"]
le = LabelEncoder()
y_encoded = le.fit_transform(y)
X = X.select_dtypes(include=["int64", "float64"])
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)


pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("xgb", XGBClassifier(
        objective="binary:logistic",
        eval_metric="logloss",
        use_label_encoder=False,
        random_state=42,

    ))
])

param_grid = {
    "xgb__n_estimators": [100, 200, 300],
    "xgb__max_depth": [3, 5, 7],
    "xgb__learning_rate": [0.01, 0.05, 0.1],
    "xgb__subsample": [0.7, 0.8, 1],
    "xgb__colsample_bytree": [0.7, 0.8, 1]
}


grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring="f1_weighted", n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)


print("Best Parameters:", grid_search.best_params_)
print("Best F1-Weighted Score:", grid_search.best_score_)


y_pred = grid_search.predict(X_test)
print("Test Classification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 243 candidates, totalling 1215 fits
Best Parameters: {'xgb__colsample_bytree': 0.7, 'xgb__learning_rate': 0.1, 'xgb__max_depth': 7, 'xgb__n_estimators': 300, 'xgb__subsample': 0.8}
Best F1-Weighted Score: 0.7740815636532379
Test Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.56      0.65       263
           1       0.65      0.50      0.57       226
           2       0.81      0.92      0.86       939

    accuracy                           0.79      1428
   macro avg       0.75      0.66      0.69      1428
weighted avg       0.78      0.79      0.78      1428

In [ ]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
target_col='tfopwg_disp'
X = Tess.drop(columns=[target_col])
y = Tess[target_col]
X = X.select_dtypes(include=["int64", "float64"])

In [ ]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

In [ ]:
Tess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7699 entries, 0 to 7698
Data columns (total 24 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   toi          7699 non-null   float64
 1   toipfx       7699 non-null   float64
 2   tid          7699 non-null   float64
 3   ctoi_alias   7699 non-null   float64
 4   pl_pnum      7699 non-null   float64
 5   tfopwg_disp  7699 non-null   object
 6   rastr        7699 non-null   object
 7   ra           7699 non-null   float64
 8   decstr       7699 non-null   object
 9   dec          7699 non-null   float64
 10  st_pmra      7699 non-null   float64
 11  st_pmdec     7699 non-null   float64
 12  pl_tranmid   7699 non-null   float64
 13  pl_orbper    7699 non-null   float64
 14  pl_trandurh  7699 non-null   float64
 15  pl_trandep   7699 non-null   float64
 16  pl_rade      7699 non-null   float64
 17  pl_insol     7699 non-null   float64
 18  pl_eqt       7699 non-null   float64
 19  st_tmag      7699 non-null   float64
 20  st_dist      7699 non-null   float64
 21  st_teff      7699 non-null   float64
 22  st_logg      7699 non-null   float64
 23  st_rad       7699 non-null   float64
dtypes: float64(21), object(3)
memory usage: 1.4+ MB

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

In [ ]:
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"
)
gb = GradientBoostingClassifier(
    n_estimators=250,
    learning_rate=0.05,
    random_state=42
)
lr = LogisticRegression(max_iter=500, class_weight="balanced",C=0.5)
ensemble = VotingClassifier( estimators=[("rf", rf), ("gb", gb), ("lr", lr)], voting="soft" )

In [ ]:
pipeline = Pipeline([ ("scaler", StandardScaler()), ("clf", ensemble) ])
scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring="accuracy")
print("Cross-validation accuracy:", np.mean(scores))

Cross-validation accuracy: 0.7963775023832221

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
pipeline.fit(X_train, y_train)

y_train_pred = pipeline.predict(X_train)
y_test_pred = pipeline.predict(X_test)

# Accuracy
print("Train accuracy:", pipeline.score(X_train, y_train))
print("Test accuracy:", pipeline.score(X_test, y_test))

# Precision
print("Train precision:", precision_score(y_train, y_train_pred, average='weighted'))
print("Test precision:", precision_score(y_test, y_test_pred, average='weighted'))

# Recall
print("Train recall:", recall_score(y_train, y_train_pred, average='weighted'))
print("Test recall:", recall_score(y_test, y_test_pred, average='weighted'))

# Optional: F1-score
print("Train F1-score:", f1_score(y_train, y_train_pred, average='weighted'))
print("Test F1-score:", f1_score(y_test, y_test_pred, average='weighted'))

Train accuracy: 0.917254528122021
Test accuracy: 0.7926829268292683
Train precision: 0.9162773027556793
Test precision: 0.7806774485544912
Train recall: 0.917254528122021
Test recall: 0.7926829268292683
Train F1-score: 0.9151737004503191
Test F1-score: 0.7841547769228121

In [ ]:
import joblib
joblib.dump(pipeline, "exoplanet_Tess_ensemble_model.pkl")
joblib.dump(le, "label_Tess_ensamble_encoder.pkl")
print("✅ Model and encoder saved!")

✅ Model and encoder saved!

In [ ]:
mask = ~((Tess['tfopwg_disp'] == 'CANDIDATE') )
filtered_data = Tess[mask].copy()

In [ ]:
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report


extra_trees = ExtraTreesClassifier(random_state=42, class_weight="balanced")
gb = GradientBoostingClassifier(random_state=42)
lr = LogisticRegression(max_iter=500, class_weight="balanced", solver="liblinear")
knn = KNeighborsClassifier()
svc = SVC(probability=True, class_weight="balanced", random_state=42)

# Ensemble using VotingClassifier
ensemble = VotingClassifier(
    estimators=[
        ("et", extra_trees),
        ("gb", gb),
        ("lr", lr),
        ("knn", knn),
        ("svc", svc)
    ],
    voting="soft"
)

# Pipeline
pipeline = Pipeline([
    ("imputer", IterativeImputer(random_state=42)),
    ("scaler", StandardScaler()),
    ("ensemble", ensemble)
])

# Grid search parameters (example: you can expand)
param_grid = {
    "ensemble__et__n_estimators": [100, 200],
    "ensemble__gb__n_estimators": [100, 200],
    "ensemble__lr__C": [0.1, 1],
    "ensemble__knn__n_neighbors": [3, 5],
    "ensemble__svc__C": [0.1, 1]
}

# GridSearchCV
grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="f1_weighted",
    n_jobs=-1,
    verbose=2
)

# Fit the model
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best F1-Weighted Score:", grid_search.best_score_)

# Evaluate on test set
y_pred = grid_search.predict(X_test)
print("Test Classification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 32 candidates, totalling 160 fits
Best Parameters: {'ensemble__et__n_estimators': 200, 'ensemble__gb__n_estimators': 200, 'ensemble__knn__n_neighbors': 5, 'ensemble__lr__C': 1, 'ensemble__svc__C': 1}
Best F1-Weighted Score: 0.784060762309608
Test Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.46      0.54       142
           1       0.74      0.54      0.63       243
           2       0.84      0.94      0.88       927

    accuracy                           0.81      1312
   macro avg       0.75      0.65      0.68      1312
weighted avg       0.80      0.81      0.80      1312

In [ ]:
import joblib
joblib.dump(grid_search, "exoplanet_Tess_FP_Confirmed_ensemble_model.pkl")
joblib.dump(le, "label_Tess_FP_Confirmed_ensamble_encoder.pkl")
print("✅ Model and encoder saved!")

✅ Model and encoder saved!